### ISSUE TITLE
[Teldrassil] [NPC] Zarrin&Nyoma

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#3074]
Issue: When talking to these two npcs nothing happens, no dialog window opens or it's hidden as they react as if the dialog window has opened. They both stand next to each other.

Zarrin (Cooking Trainer)
Nyoma (Cooking Supplies)

http://www.wowhead.com/npc=6286/zarrin
http://www.wowhead.com/npc=4265/nyoma

**Comment by Guybrush-Hellscream** [comment]
Fixed in next update. :palm_tree:

**Comment by phikaro** [comment]
You guys are fast, keep up the good work. =)

**Comment by phikaro** [comment]
Well after the new update, the two npcs are still having the same issue, dialog window does not open, I make sure that I deleted my cache folder.

**Comment by Guybrush-Hellscream** [comment]
They're working for me, try to go far from the NPCs and come back to refresh it.

**Comment by phikaro** [comment]
Yea it works now, it needed refreshing. =)
