### ISSUE TITLE
Druid Ferocius Bite Energy cost (DMG boost)

### ISSUE THREAD

**Issue by Aprophys** [HellscreamWoW/Tracker#4026]
Ferocius Bite Ignores the max. Energy dempaning from 50 energy.
http://www.wowhead.com/spell=22568/ferocious-bite
At the moment FB dumps all (max 100) energy.
http://imgur.com/a/M5VOi

**Comment by Collector-Hellscream** [comment]
Issue #3937 might be connected.

**Comment by Aprophys** [comment]
Oh okay i dont see that post sry if its so u can close this ticket :)

**Comment by EPS1L0N** [comment]
Spent about an hour and a half trying to reproduce your guys' bugs, the only thing i noticed that was wrong is that you're always getting 2 cp from shred / rake, when you're only supposed to get 1 unless it's a crit. I fixed that. here's a snippet of my testing, chat has the amount of energy feroc is taking & how much of a bonus it's getting. recommend watching in HD

ref #3937

[![Feral Druid Test](http://img.youtube.com/vi/VS7EEqNk0Io/0.jpg)](https://www.youtube.com/watch?v=VS7EEqNk0Io)

**Comment by Collector-Hellscream** [comment]
#3938 :D
I will check if I still have that issue #3937 today. Sometimes it's working as it should and sometimes it doesn't (like fishing). About #4026 can't tell anything because I didn't noticed that too but that consuming more energy than it should sounds similar to my problem.

**Comment by EPS1L0N** [comment]
#2266
