### ISSUE TITLE
[NPC] Kelara

### ISSUE THREAD

**Issue by Luminescent-Hellscream** [HellscreamWoW/Tracker#4039]
the npc [Kelara](http://www.wowhead.com/npc=21906/kelara) after right clicking no her has no scripting to show her items for sale

**Comment by Tregeta** [comment]
Seems like it works for me, try clearing cache. I did notice that it is lacking most all class set data, that will be rectified soon.

**Comment by Tregeta** [comment]
fixed in next update

**Comment by Luminescent-Hellscream** [comment]
Just tested again at 7:37AM server time and still the same nothing pops up at all even after clearing the cache and using hellscreams launcher.
