### ISSUE TITLE
Quest: Fel Moss Corruption

### ISSUE THREAD

**Issue by phikaro** [HellscreamWoW/Tracker#918]
Issue: When finishing this quest and turning it in, after you hit the complete button, the dialog window is not closing.

http://www.wowhead.com/quest=28714/fel-moss-corruption

**Comment by Guybrush-Hellscream** [comment]
Fixed since (Patch 010520)[http://www.hellscream-wow.com/log#2015.12.05.010520]

**Comment by phikaro** [comment]
Nope it's not, few days ago I did the quest and still not fixed.

**Comment by Guybrush-Hellscream** [comment]
I just did it 6 hours ago and the dialog window disappeared when I finished it.

**Comment by Malae1** [comment]
it's recommended that you clear your cache before logging on. If you didn't do that, it's suggested that you do.
